name: 'fetch-patrons'
description: 'Fetch a list of patrons from the Patreon API and and create a new file and directory to store the list in a Lua table.'
branding:
  icon: package
  color: orange
runs:
  using: 'node20'
  main: 'dist/index.js'
