name: Build Dist
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'dist/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'dist/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v4
        with:
          name: action.yml
          path: action.yml

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    env:
      MY_GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ env.MY_GH_TOKEN }}
          commit-message: 'build: update distribution'
          title: Update Distribution
          body: |
            - Updates the distribution for changes on `main`
          branch: update-distribution
          delete-branch: true

      - name: Auto Merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.MY_GH_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
